--MANIPULANDO STRINGS COM SQL 

--JUNTAR INFORMAÇAO DE 2 COLUNAS 
SELECT CONCAT(FirstName,' ', LastName) 
FROM Person.Person

--CAIXA ALTA 
SELECT UPPER(FirstName)
FROM Person.Person

--CAIXA BAIXA 
SELECT LOWER(FirstName)
FROM Person.Person

--LER TAMANHO DA STRING 
SELECT LEN(FirstName)
FROM Person.Person

--SELECIONAR POSIÇOES DO STRING 
SELECT SUBSTRING(FirstName,1,3)
FROM Person.Person

--SUBSTITUIR STRING POR OUTRA STRING 
SELECT REPLACE(PRODUCTNUMBER, '-', '#')
FROM Production.Product
